server:
  port: 5200

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: ENC(/GRtfuunCsguUWKaGQifWg==)
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: ENC(/GRtfuunCsguUWKaGQifWg==)
      driver-class-name: com.mysql.cj.jdbc.Driver

primarydb:
  uniqueResourceName: primary
  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: test
    password: ENC(/GRtfuunCsguUWKaGQifWg==)
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

secondarydb:
  uniqueResourceName: secondary
  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://127.0.0.1:3306/springboot2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: test
    password: ENC(/GRtfuunCsguUWKaGQifWg==)
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.zimug.bootlaunch: debug

jasypt:
  encryptor:
    password: 123456