server:
  port: 5200

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    primary:
      url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: ENC(/GRtfuunCsguUWKaGQifWg==)
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://127.0.0.1:3306/springboot2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: ENC(/GRtfuunCsguUWKaGQifWg==)
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60

jasypt:
  encryptor:
    password: 123456