server:
  port: 5200

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test
    password: ENC(/GRtfuunCsguUWKaGQifWg==)
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:generator/*.xml

  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.zimug.bootlaunch: debug

context:
  listener:
    classes: cn.littlegreenmouse.hello.customlistener.MyListener3

jasypt:
  encryptor:
    password: 123456